/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsrDocumentation) {
      root.AsrDocumentation = {};
    }
    root.AsrDocumentation.PackageDto = factory(root.AsrDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PackageDto model module.
   * @module model/PackageDto
   * @version 1.0.dev
   */

  /**
   * Constructs a new <code>PackageDto</code>.
   * @alias module:model/PackageDto
   * @class
   * @param packageId {String} Package ID
   * @param name {String} Package name
   * @param language {String} Package language
   * @param sampleRate {Number} Required sample rate of data
   * @param loaded {Boolean} Is package loaded to the cache
   */
  var exports = function(packageId, name, language, sampleRate, loaded) {
    var _this = this;

    _this['package_id'] = packageId;
    _this['name'] = name;
    _this['language'] = language;
    _this['sample_rate'] = sampleRate;
    _this['loaded'] = loaded;
  };

  /**
   * Constructs a <code>PackageDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageDto} obj Optional instance to populate.
   * @return {module:model/PackageDto} The populated <code>PackageDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('package_id')) {
        obj['package_id'] = ApiClient.convertToType(data['package_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('sample_rate')) {
        obj['sample_rate'] = ApiClient.convertToType(data['sample_rate'], 'Number');
      }
      if (data.hasOwnProperty('loaded')) {
        obj['loaded'] = ApiClient.convertToType(data['loaded'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Package ID
   * @member {String} package_id
   */
  exports.prototype['package_id'] = undefined;
  /**
   * Package name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Package language
   * @member {String} language
   */
  exports.prototype['language'] = undefined;
  /**
   * Required sample rate of data
   * @member {Number} sample_rate
   */
  exports.prototype['sample_rate'] = undefined;
  /**
   * Is package loaded to the cache
   * @member {Boolean} loaded
   */
  exports.prototype['loaded'] = undefined;



  return exports;
}));


