/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RecognitionRequestDto', 'model/StartSessionRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RecognitionRequestDto'), require('./StartSessionRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.AsrDocumentation) {
      root.AsrDocumentation = {};
    }
    root.AsrDocumentation.SessionlessRecognitionRequestDto = factory(root.AsrDocumentation.ApiClient, root.AsrDocumentation.RecognitionRequestDto, root.AsrDocumentation.StartSessionRequest);
  }
}(this, function(ApiClient, RecognitionRequestDto, StartSessionRequest) {
  'use strict';




  /**
   * The SessionlessRecognitionRequestDto model module.
   * @module model/SessionlessRecognitionRequestDto
   * @version 1.0.dev
   */

  /**
   * Constructs a new <code>SessionlessRecognitionRequestDto</code>.
   * @alias module:model/SessionlessRecognitionRequestDto
   * @class
   * @param userInfo {module:model/StartSessionRequest} User credentials
   * @param recognitionRequest {module:model/RecognitionRequestDto} User credentials
   */
  var exports = function(userInfo, recognitionRequest) {
    var _this = this;

    _this['user_info'] = userInfo;
    _this['recognition_request'] = recognitionRequest;
  };

  /**
   * Constructs a <code>SessionlessRecognitionRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionlessRecognitionRequestDto} obj Optional instance to populate.
   * @return {module:model/SessionlessRecognitionRequestDto} The populated <code>SessionlessRecognitionRequestDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user_info')) {
        obj['user_info'] = StartSessionRequest.constructFromObject(data['user_info']);
      }
      if (data.hasOwnProperty('recognition_request')) {
        obj['recognition_request'] = RecognitionRequestDto.constructFromObject(data['recognition_request']);
      }
    }
    return obj;
  }

  /**
   * User credentials
   * @member {module:model/StartSessionRequest} user_info
   */
  exports.prototype['user_info'] = undefined;
  /**
   * User credentials
   * @member {module:model/RecognitionRequestDto} recognition_request
   */
  exports.prototype['recognition_request'] = undefined;



  return exports;
}));


