/**
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TtsDocumentation) {
      root.TtsDocumentation = {};
    }
    root.TtsDocumentation.Credentials = factory(root.TtsDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Credentials model module.
   * @module model/Credentials
   * @version 3.1.73
   */

  /**
   * Constructs a new <code>Credentials</code>.
   * @alias module:model/Credentials
   * @class
   * @param username {String} Username
   * @param password {String} Password
   * @param domainId {String} Domain ID
   */
  var exports = function(username, password, domainId) {
    var _this = this;

    _this['username'] = username;
    _this['password'] = password;
    _this['domain_id'] = domainId;
  };

  /**
   * Constructs a <code>Credentials</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Credentials} obj Optional instance to populate.
   * @return {module:model/Credentials} The populated <code>Credentials</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('domain_id')) {
        obj['domain_id'] = ApiClient.convertToType(data['domain_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Username
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * Password
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * Domain ID
   * @member {String} domain_id
   */
  exports.prototype['domain_id'] = undefined;



  return exports;
}));


