/**
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TtsDocumentation) {
      root.TtsDocumentation = {};
    }
    root.TtsDocumentation.SynthesizeVoiceType = factory(root.TtsDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SynthesizeVoiceType model module.
   * @module model/SynthesizeVoiceType
   * @version 3.1.73
   */

  /**
   * Constructs a new <code>SynthesizeVoiceType</code>.
   * @alias module:model/SynthesizeVoiceType
   * @class
   * @param id {String} Voice id
   * @param name {String} Name of voice
   * @param gender {module:model/SynthesizeVoiceType.GenderEnum} Gender of voice
   */
  var exports = function(id, name, gender) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['gender'] = gender;
  };

  /**
   * Constructs a <code>SynthesizeVoiceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SynthesizeVoiceType} obj Optional instance to populate.
   * @return {module:model/SynthesizeVoiceType} The populated <code>SynthesizeVoiceType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
    }
    return obj;
  }

  /**
   * Voice id
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of voice
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Gender of voice
   * @member {module:model/SynthesizeVoiceType.GenderEnum} gender
   */
  exports.prototype['gender'] = undefined;


  /**
   * Allowed values for the <code>gender</code> property.
   * @enum {String}
   * @readonly
   */
  exports.GenderEnum = {
    /**
     * value: "UNDEFINED"
     * @const
     */
    "UNDEFINED": "UNDEFINED",
    /**
     * value: "MALE"
     * @const
     */
    "MALE": "MALE",
    /**
     * value: "FEMALE"
     * @const
     */
    "FEMALE": "FEMALE"  };


  return exports;
}));


