/**
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SynthesizeText'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SynthesizeText'));
  } else {
    // Browser globals (root is window)
    if (!root.TtsDocumentation) {
      root.TtsDocumentation = {};
    }
    root.TtsDocumentation.SynthesizeRequest = factory(root.TtsDocumentation.ApiClient, root.TtsDocumentation.SynthesizeText);
  }
}(this, function(ApiClient, SynthesizeText) {
  'use strict';




  /**
   * The SynthesizeRequest model module.
   * @module model/SynthesizeRequest
   * @version 3.1.73
   */

  /**
   * Constructs a new <code>SynthesizeRequest</code>.
   * @alias module:model/SynthesizeRequest
   * @class
   * @param text {module:model/SynthesizeText} Text for synthesize to speech
   * @param voiceName {String} Name of name
   * @param audio {String} Format of response audio
   */
  var exports = function(text, voiceName, audio) {
    var _this = this;

    _this['text'] = text;
    _this['voice_name'] = voiceName;
    _this['audio'] = audio;
  };

  /**
   * Constructs a <code>SynthesizeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SynthesizeRequest} obj Optional instance to populate.
   * @return {module:model/SynthesizeRequest} The populated <code>SynthesizeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('text')) {
        obj['text'] = SynthesizeText.constructFromObject(data['text']);
      }
      if (data.hasOwnProperty('voice_name')) {
        obj['voice_name'] = ApiClient.convertToType(data['voice_name'], 'String');
      }
      if (data.hasOwnProperty('audio')) {
        obj['audio'] = ApiClient.convertToType(data['audio'], 'String');
      }
    }
    return obj;
  }

  /**
   * Text for synthesize to speech
   * @member {module:model/SynthesizeText} text
   */
  exports.prototype['text'] = undefined;
  /**
   * Name of name
   * @member {String} voice_name
   */
  exports.prototype['voice_name'] = undefined;
  /**
   * Format of response audio
   * @member {String} audio
   */
  exports.prototype['audio'] = undefined;



  return exports;
}));


