/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.AuthRequestDto = factory(root.DiarizationDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AuthRequestDto model module.
   * @module model/AuthRequestDto
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>AuthRequestDto</code>.
   * User information provided on authentication
   * @alias module:model/AuthRequestDto
   * @class
   * @param username {String} User name
   * @param domainId {Number} User domain
   * @param password {String} User password - planed text
   */
  var exports = function(username, domainId, password) {
    var _this = this;

    _this['username'] = username;
    _this['domain_id'] = domainId;
    _this['password'] = password;
  };

  /**
   * Constructs a <code>AuthRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthRequestDto} obj Optional instance to populate.
   * @return {module:model/AuthRequestDto} The populated <code>AuthRequestDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('domain_id')) {
        obj['domain_id'] = ApiClient.convertToType(data['domain_id'], 'Number');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * User name
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * User domain
   * @member {Number} domain_id
   */
  exports.prototype['domain_id'] = undefined;
  /**
   * User password - planed text
   * @member {String} password
   */
  exports.prototype['password'] = undefined;



  return exports;
}));


