/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SpeakerDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SpeakerDto'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.DiarizationResponseDto = factory(root.DiarizationDocumentation.ApiClient, root.DiarizationDocumentation.SpeakerDto);
  }
}(this, function(ApiClient, SpeakerDto) {
  'use strict';




  /**
   * The DiarizationResponseDto model module.
   * @module model/DiarizationResponseDto
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>DiarizationResponseDto</code>.
   * @alias module:model/DiarizationResponseDto
   * @class
   * @param speakers {Array.<module:model/SpeakerDto>} List of speakers found in record
   */
  var exports = function(speakers) {
    var _this = this;

    _this['speakers'] = speakers;
  };

  /**
   * Constructs a <code>DiarizationResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DiarizationResponseDto} obj Optional instance to populate.
   * @return {module:model/DiarizationResponseDto} The populated <code>DiarizationResponseDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('speakers')) {
        obj['speakers'] = ApiClient.convertToType(data['speakers'], [SpeakerDto]);
      }
    }
    return obj;
  }

  /**
   * List of speakers found in record
   * @member {Array.<module:model/SpeakerDto>} speakers
   */
  exports.prototype['speakers'] = undefined;



  return exports;
}));


