/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.ModuleNamesDto = factory(root.DiarizationDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModuleNamesDto model module.
   * @module model/ModuleNamesDto
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>ModuleNamesDto</code>.
   * Object for module names transport
   * @alias module:model/ModuleNamesDto
   * @class
   * @param names {Array.<String>} Module names
   */
  var exports = function(names) {
    var _this = this;

    _this['names'] = names;
  };

  /**
   * Constructs a <code>ModuleNamesDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModuleNamesDto} obj Optional instance to populate.
   * @return {module:model/ModuleNamesDto} The populated <code>ModuleNamesDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('names')) {
        obj['names'] = ApiClient.convertToType(data['names'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Module names
   * @member {Array.<String>} names
   */
  exports.prototype['names'] = undefined;



  return exports;
}));


