/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 999999
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SessionServiceDocumentation) {
      root.SessionServiceDocumentation = {};
    }
    root.SessionServiceDocumentation.AdvancedRecognitionRequestDto = factory(root.SessionServiceDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AdvancedRecognitionRequestDto model module.
   * @module model/AdvancedRecognitionRequestDto
   * @version 999999
   */

  /**
   * Constructs a new <code>AdvancedRecognitionRequestDto</code>.
   * @alias module:model/AdvancedRecognitionRequestDto
   * @class
   * @param data {Blob} Binary audio file as Base64 string
   */
  var exports = function(data, channels, packageId) {
    var _this = this;

    _this['package_id'] = packageId;
    _this['channels'] = channels;

    _this['data'] = data;
  };

  /**
   * Constructs a <code>AdvancedRecognitionRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdvancedRecognitionRequestDto} obj Optional instance to populate.
   * @return {module:model/AdvancedRecognitionRequestDto} The populated <code>AdvancedRecognitionRequestDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('package_id')) {
        obj['package_id'] = ApiClient.convertToType(data['package_id'], 'String');
      }
      if (data.hasOwnProperty('channels')) {
        obj['channels'] = ApiClient.convertToType(data['channels'], ['Number']);
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * Recognize with package
   * @member {String} package_id
   */
  exports.prototype['package_id'] = undefined;
  /**
   * Specific channels to process
   * @member {Array.<Number>} channels
   */
  exports.prototype['channels'] = new Array(0, 1);
  /**
   * Binary audio file as Base64 string
   * @member {Blob} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


