/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 999999
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WordDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WordDto'));
  } else {
    // Browser globals (root is window)
    if (!root.SessionServiceDocumentation) {
      root.SessionServiceDocumentation = {};
    }
    root.SessionServiceDocumentation.ASRAdvancedResultDto = factory(root.SessionServiceDocumentation.ApiClient,
        root.SessionServiceDocumentation.WordDto);
  }
}(this, function(ApiClient, WordDto) {
  'use strict';




  /**
   * The ASRAdvancedResultDto model module.
   * @module model/ASRAdvancedResultDto
   * @version 999999
   */

  /**
   * Constructs a new <code>ASRAdvancedResultDto</code>.
   * @alias module:model/ASRAdvancedResultDto
   * @class
   * @param channelId {Number} Channel id
   * @param result {Array.<module:model/WordDto>} Recognition result
   */
  var exports = function(channelId, result) {
    var _this = this;

    _this['channel_id'] = channelId;
    _this['result'] = result;
  };

  /**
   * Constructs a <code>ASRAdvancedResultDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ASRAdvancedResultDto} obj Optional instance to populate.
   * @return {module:model/ASRAdvancedResultDto} The populated <code>ASRAdvancedResultDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('channel_id')) {
        obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'Number');
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = ApiClient.convertToType(data['result'], [WordDto]);
      }
    }
    return obj;
  }

  /**
   * Channel id
   * @member {Number} channel_id
   */
  exports.prototype['channel_id'] = undefined;
  /**
   * Recognition result
   * @member {Array.<module:model/WordDto>} result
   */
  exports.prototype['result'] = undefined;



  return exports;
}));


