/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 999999
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsrDocumentation) {
      root.AsrDocumentation = {};
    }
    root.AsrDocumentation.AudioFileDto = factory(root.AsrDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AudioFileDto model module.
   * @module model/AudioFileDto
   * @version 999999
   */

  /**
   * Constructs a new <code>AudioFileDto</code>.
   * @alias module:model/AudioFileDto
   * @class
   * @param data {Blob} Binary audio file as Base64 string
   */
  var exports = function(data) {
    var _this = this;

    _this['data'] = data;

  };

  /**
   * Constructs a <code>AudioFileDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AudioFileDto} obj Optional instance to populate.
   * @return {module:model/AudioFileDto} The populated <code>AudioFileDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
      }
      if (data.hasOwnProperty('mime')) {
        obj['mime'] = ApiClient.convertToType(data['mime'], 'String');
      }
    }
    return obj;
  }

  /**
   * Binary audio file as Base64 string
   * @member {Blob} data
   */
  exports.prototype['data'] = undefined;
  /**
   * Audio file mime type
   * @member {String} mime
   */
  exports.prototype['mime'] = undefined;



  return exports;
}));


