/**
 * SessionService documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.158
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SessionServiceDocumentation) {
      root.SessionServiceDocumentation = {};
    }
    root.SessionServiceDocumentation.AuthResponseDto = factory(root.SessionServiceDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AuthResponseDto model module.
   * @module model/AuthResponseDto
   * @version 3.2.158
   */

  /**
   * Constructs a new <code>AuthResponseDto</code>.
   * Auth information provided after authentication
   * @alias module:model/AuthResponseDto
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AuthResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthResponseDto} obj Optional instance to populate.
   * @return {module:model/AuthResponseDto} The populated <code>AuthResponseDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('session_id')) {
        obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Session identifier to be provided in header on all REST API results
   * @member {String} session_id
   */
  exports.prototype['session_id'] = undefined;



  return exports;
}));


