/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 999999
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AudioFileDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AudioFileDto'));
  } else {
    // Browser globals (root is window)
    if (!root.AsrDocumentation) {
      root.AsrDocumentation = {};
    }
    root.AsrDocumentation.RecognitionRequestDto = factory(root.AsrDocumentation.ApiClient, root.AsrDocumentation.AudioFileDto);
  }
}(this, function(ApiClient, AudioFileDto) {
  'use strict';




  /**
   * The RecognitionRequestDto model module.
   * @module model/RecognitionRequestDto
   * @version 999999
   */

  /**
   * Constructs a new <code>RecognitionRequestDto</code>.
   * @alias module:model/RecognitionRequestDto
   * @class
   * @param audio {module:model/AudioFileDto} Audio file data and description
   */
  var exports = function(audio, package_id) {
    var _this = this;

    _this['audio'] = audio;
    _this['package_id'] = package_id;

  };

  /**
   * Constructs a <code>RecognitionRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecognitionRequestDto} obj Optional instance to populate.
   * @return {module:model/RecognitionRequestDto} The populated <code>RecognitionRequestDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('audio')) {
        obj['audio'] = AudioFileDto.constructFromObject(data['audio']);
      }
      if (data.hasOwnProperty('package_id')) {
        obj['package_id'] = ApiClient.convertToType(data['package_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Audio file data and description
   * @member {module:model/AudioFileDto} audio
   */
  exports.prototype['audio'] = undefined;
  /**
   * Recognize with package
   * @member {String} package_id
   */
  exports.prototype['package_id'] = undefined;



  return exports;
}));


