/**
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 999999
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsrDocumentation) {
      root.AsrDocumentation = {};
    }
    root.AsrDocumentation.WordDto = factory(root.AsrDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WordDto model module.
   * @module model/WordDto
   * @version 999999
   */

  /**
   * Constructs a new <code>WordDto</code>.
   * @alias module:model/WordDto
   * @class
   * @param word {String} Recognized word
   * @param score {String} Recognition confidence (0 - 100.00)
   */
  var exports = function(word, score) {
    var _this = this;

    _this['word'] = word;

    _this['score'] = score;



  };

  /**
   * Constructs a <code>WordDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WordDto} obj Optional instance to populate.
   * @return {module:model/WordDto} The populated <code>WordDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('word')) {
        obj['word'] = ApiClient.convertToType(data['word'], 'String');
      }
      if (data.hasOwnProperty('speaker')) {
        obj['speaker'] = ApiClient.convertToType(data['speaker'], 'Number');
      }
      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'String');
      }
      if (data.hasOwnProperty('begin')) {
        obj['begin'] = ApiClient.convertToType(data['begin'], 'String');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'String');
      }
      if (data.hasOwnProperty('stop_sign')) {
        obj['stop_sign'] = ApiClient.convertToType(data['stop_sign'], 'String');
      }
    }
    return obj;
  }

  /**
   * Recognized word
   * @member {String} word
   */
  exports.prototype['word'] = undefined;
  /**
   * Identified speaker id
   * @member {Number} speaker
   */
  exports.prototype['speaker'] = undefined;
  /**
   * Recognition confidence (0 - 100.00)
   * @member {String} score
   */
  exports.prototype['score'] = undefined;
  /**
   * Time stamp on which this word was found
   * @member {String} begin
   */
  exports.prototype['begin'] = undefined;
  /**
   * Word duration
   * @member {String} length
   */
  exports.prototype['length'] = undefined;
  /**
   * Word stop sign
   * @member {String} stop_sign
   */
  exports.prototype['stop_sign'] = undefined;



  return exports;
}));


