/**
 * SessionService documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.158
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['ApiClient', 'model/AuthRequestDto', 'model/AuthResponseDto', 'model/AuthStatusDto', 'model/DomainDto', 'model/MessageDto',
            'model/ModuleNamesDto', 'api/ASRClient', 'model/ASRAdvancedResultDto', 'model/ASRResultDto', 'model/AdvancedRecognitionRequestDto',
            'model/AudioFileDto', 'model/MessageDto', 'model/PackageDto', 'model/RecognitionRequestDto', 'model/SessionlessRecognitionRequestDto',
            'model/StartSessionRequest', 'model/StatusDto', 'model/StreamRequestDto',
            'model/StreamResponseDto', 'model/WordDto'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('./ApiClient'), require('./model/AuthRequestDto'), require('./model/AuthResponseDto'), require('./model/AuthStatusDto'),
            require('./model/DomainDto'), require('./model/MessageDto'), require('./model/ModuleNamesDto'), require('./api/ASRClient'),
            require('./model/ASRAdvancedResultDto'), require('./model/ASRResultDto'), require('./model/AdvancedRecognitionRequestDto'), require('./model/AudioFileDto'),
            require('./model/MessageDto'), require('./model/PackageDto'), require('./model/RecognitionRequestDto'), require('./model/SessionlessRecognitionRequestDto'),
            require('./model/StartSessionRequest'), require('./model/StatusDto'), require('./model/StreamRequestDto'), require('./model/StreamResponseDto'),
            require('./model/WordDto'));
    }
}(function (ApiClient, AuthRequestDto, AuthResponseDto, AuthStatusDto, DomainDto, MessageDto, ModuleNamesDto, ASRClient,
            ASRAdvancedResultDto, ASRResultDto, AdvancedRecognitionRequestDto, AudioFileDto, PackageDto,
            RecognitionRequestDto, SessionlessRecognitionRequestDto, StartSessionRequest, StatusDto, StreamRequestDto,
            StreamResponseDto, WordDto) {
    'use strict';

    /**
     * ERROR_UNKNOWN.<br>
     * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
     * <p>
     * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
     * <pre>
     * var SessionServiceDocumentation = require('index'); // See note below*.
     * var xxxSvc = new SessionServiceDocumentation.XxxApi(); // Allocate the API class we're going to use.
     * var yyyModel = new SessionServiceDocumentation.Yyy(); // Construct a model instance.
     * yyyModel.someProperty = 'someValue';
     * ...
     * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
     * ...
     * </pre>
     * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
     * and put the application logic within the callback function.</em>
     * </p>
     * <p>
     * A non-AMD browser application (discouraged) might do something like this:
     * <pre>
     * var xxxSvc = new SessionServiceDocumentation.XxxApi(); // Allocate the API class we're going to use.
     * var yyy = new SessionServiceDocumentation.Yyy(); // Construct a model instance.
     * yyyModel.someProperty = 'someValue';
     * ...
     * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
     * ...
     * </pre>
     * </p>
     * @module index
     * @version 3.2.158
     */
    var exports = {
        /**
         * The ApiClient constructor.
         * @property {module:ApiClient}
         */
        ApiClient: ApiClient,
        /**
         * The AuthRequestDto model constructor.
         * @property {module:model/AuthRequestDto}
         */
        AuthRequestDto: AuthRequestDto,
        /**
         * The AuthResponseDto model constructor.
         * @property {module:model/AuthResponseDto}
         */
        AuthResponseDto: AuthResponseDto,
        /**
         * The AuthStatusDto model constructor.
         * @property {module:model/AuthStatusDto}
         */
        AuthStatusDto: AuthStatusDto,
        /**
         * The DomainDto model constructor.
         * @property {module:model/DomainDto}
         */
        DomainDto: DomainDto,
        /**
         * The MessageDto model constructor.
         * @property {module:model/MessageDto}
         */
        MessageDto: MessageDto,
        /**
         * The ModuleNamesDto model constructor.
         * @property {module:model/ModuleNamesDto}
         */
        ModuleNamesDto: ModuleNamesDto,
        /**
         * The SessionApi service constructor.
         * @property {module:api/SessionApi}
         */
        ASRClient: ASRClient,
        /**
         * The ASRAdvancedResultDto model constructor.
         * @property {module:model/ASRAdvancedResultDto}
         */
        ASRAdvancedResultDto: ASRAdvancedResultDto,
        /**
         * The ASRResultDto model constructor.
         * @property {module:model/ASRResultDto}
         */
        ASRResultDto: ASRResultDto,
        /**
         * The AdvancedRecognitionRequestDto model constructor.
         * @property {module:model/AdvancedRecognitionRequestDto}
         */
        AdvancedRecognitionRequestDto: AdvancedRecognitionRequestDto,
        /**
         * The AudioFileDto model constructor.
         * @property {module:model/AudioFileDto}
         */
        AudioFileDto: AudioFileDto,
        /**
         * The PackageDto model constructor.
         * @property {module:model/PackageDto}
         */
        PackageDto: PackageDto,
        /**
         * The RecognitionRequestDto model constructor.
         * @property {module:model/RecognitionRequestDto}
         */
        RecognitionRequestDto: RecognitionRequestDto,
        /**
         * The SessionlessRecognitionRequestDto model constructor.
         * @property {module:model/SessionlessRecognitionRequestDto}
         */
        SessionlessRecognitionRequestDto: SessionlessRecognitionRequestDto,
        /**
         * The StartSessionRequest model constructor.
         * @property {module:model/StartSessionRequest}
         */
        StartSessionRequest: StartSessionRequest,
        /**
         * The StatusDto model constructor.
         * @property {module:model/StatusDto}
         */
        StatusDto: StatusDto,
        /**
         * The StreamRequestDto model constructor.
         * @property {module:model/StreamRequestDto}
         */
        StreamRequestDto: StreamRequestDto,
        /**
         * The StreamResponseDto model constructor.
         * @property {module:model/StreamResponseDto}
         */
        StreamResponseDto: StreamResponseDto,
        /**
         * The WordDto model constructor.
         * @property {module:model/WordDto}
         */
        WordDto: WordDto
    };

    return exports;
}));
