/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AudioDto', 'model/DiarizationResponseDto', 'model/MessageDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AudioDto'), require('../model/DiarizationResponseDto'), require('../model/MessageDto'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.DiarizationApi = factory(root.DiarizationDocumentation.ApiClient, root.DiarizationDocumentation.AudioDto, root.DiarizationDocumentation.DiarizationResponseDto, root.DiarizationDocumentation.MessageDto);
  }
}(this, function(ApiClient, AudioDto, DiarizationResponseDto, MessageDto) {
  'use strict';

  /**
   * Diarization service.
   * @module api/DiarizationApi
   * @version 1.1.0
   */

  /**
   * Constructs a new DiarizationApi. 
   * @alias module:api/DiarizationApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the diarization operation.
     * @callback module:api/DiarizationApi~diarizationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DiarizationResponseDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Diarization speech from sample
     * 
     * @param {String} xSessionID Session identifier
     * @param {module:model/AudioDto} body Audio file
     * @param {module:api/DiarizationApi~diarizationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DiarizationResponseDto}
     */
    this.diarization = function(xSessionID, body, callback) {
      var postBody = body;

      // verify the required parameter 'xSessionID' is set
      if (xSessionID === undefined || xSessionID === null) {
        throw new Error("Missing the required parameter 'xSessionID' when calling diarization");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling diarization");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Session-ID': xSessionID
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=UTF-8'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = DiarizationResponseDto;

      return this.apiClient.callApi(
        '/vkdiarization/rest/v1/diarization', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
