/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Speaker'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Speaker'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.DiarizationResult = factory(root.DiarizationDocumentation.ApiClient, root.DiarizationDocumentation.Speaker);
  }
}(this, function(ApiClient, Speaker) {
  'use strict';




  /**
   * The DiarizationResult model module.
   * @module model/DiarizationResult
   * @version 3.1.73
   */

  /**
   * Constructs a new <code>DiarizationResult</code>.
   * @alias module:model/DiarizationResult
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>DiarizationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DiarizationResult} obj Optional instance to populate.
   * @return {module:model/DiarizationResult} The populated <code>DiarizationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('speakers')) {
        obj['speakers'] = ApiClient.convertToType(data['speakers'], [Speaker]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Speaker>} speakers
   */
  exports.prototype['speakers'] = undefined;



  return exports;
}));


