/**
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DiarizationResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DiarizationResult'));
  } else {
    // Browser globals (root is window)
    if (!root.DiarizationDocumentation) {
      root.DiarizationDocumentation = {};
    }
    root.DiarizationDocumentation.DiarizationResponse = factory(root.DiarizationDocumentation.ApiClient, root.DiarizationDocumentation.DiarizationResult);
  }
}(this, function(ApiClient, DiarizationResult) {
  'use strict';




  /**
   * The DiarizationResponse model module.
   * @module model/DiarizationResponse
   * @version 3.1.73
   */

  /**
   * Constructs a new <code>DiarizationResponse</code>.
   * @alias module:model/DiarizationResponse
   * @class
   * @param data {module:model/DiarizationResult} Result speech in data with base64 coding
   */
  var exports = function(data) {
    var _this = this;

    _this['data'] = data;
  };

  /**
   * Constructs a <code>DiarizationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DiarizationResponse} obj Optional instance to populate.
   * @return {module:model/DiarizationResponse} The populated <code>DiarizationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = DiarizationResult.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * Result speech in data with base64 coding
   * @member {module:model/DiarizationResult} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


